version: "3"
services:
  odoo:
    image: odoo:${ODOO_VERSION}
    ports:
      - ${ODOO_HTTP_PORT}:8069
      - ${ODOO_CHAT_PORT}:8072
    depends_on:
      - db
    restart: unless-stopped
    environment:
      - HOST=db
      - USER=${ODOO_USER}
      - PASSWORD=${ODOO_PASS}
    volumes:
      - ${DATADIR}/data:/var/lib/odoo
      - ${DATADIR}/config:/etc/odoo
      - ${DATADIR}/addons:/mnt/extra-addons
      - ${DATADIR}/logs:/var/log/odoo
  db:
    image: postgres:${PG_VERSION}
    restart: unless-stopped
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=${ODOO_USER}
      - POSTGRES_PASSWORD=${ODOO_PASS}
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - ${DATADIR}/pgdata:/var/lib/postgresql/data/pgdata
